language: node_js
node_js: node
services:
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: d774466a-2d08-4ec8-bbdc-28a8a2e627e4
  app: dry-depths-20265
  on:
    repo: anthonypagano/hopindex-api
env:
  - DATABASE_URL=mongodb+srv://apagano76:76apagano@react-capstone.euuin.mongodb.net/react-capstone?retryWrites=true&w=majority
  - TEST_DATABASE_URL=mongodb+srv://apagano76:76apagano@react-capstone-test.ip7re.mongodb.net/react-capstone-test?retryWrites=true&w=majority