'use strict';
exports.API_ORIGIN = 'https://hopindex-api.vercel.app/';
exports.CLIENT_ORIGIN = 'https://hopindex-client.vercel.app/';
exports.DATABASE_URL = 'mongodb+srv://apagano76:76apagano@hopindex.jbte0v1.mongodb.net/?retryWrites=true&w=majority';
exports.PORT = process.env.PORT || 8080;
//exports.API_ORIGIN = 'https://dry-depths-20265.herokuapp.com';
//exports.CLIENT_ORIGIN = 'https://shrouded-sierra-74421.herokuapp.com';
//exports.DATABASE_URL = 'mongodb+srv://apagano76:76apagano@react-capstone.euuin.mongodb.net/react-capstone?retryWrites=true&w=majority';
//exports.TEST_DATABASE_URL = 'mongodb+srv://apagano76:76apagano@react-capstone-test.ip7re.mongodb.net/react-capstone-test?retryWrites=true&w=majority';
//exports.DATABASE_URL = 'mongodb://apagano76:76apagano@ds121282.mlab.com:21282/react-capstone';
//exports.TEST_DATABASE_URL = 'mongodb://apagano76:76apagano@ds229878.mlab.com:29878/react-capstone-test';